apiVersion: v1
kind: Service
metadata:
  name: stateset-response-gateway
  namespace: stateset-response
  labels:
    app: stateset-response-gateway
    app.kubernetes.io/name: stateset-response-gateway
spec:
  type: ClusterIP
  selector:
    app: stateset-response-gateway
  ports:
    - name: http
      port: 3000
      targetPort: http
