import { afterEach, describe, expect, it } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  buildLocalConnectorSecretEnvPlan,
  renderLocalConnectorSecretEnvPlan,
} from '../lib/workflow-studio-secret-env.js';
import { saveIntegrationsStore } from '../integrations/store.js';

const ORIGINAL_ENV = { ...process.env };

function resetEnv(): void {
  process.env = { ...ORIGINAL_ENV };
  for (const key of [
    'SHOPIFY_ACCESS_TOKEN',
    'SHOPIFY_SHOP_DOMAIN',
    'GORGIAS_DOMAIN',
    'GORGIAS_API_KEY',
    'GORGIAS_EMAIL',
    'OPENAI_API_KEY',
    'ANTHROPIC_API_KEY',
    'MEM0_API_KEY',
    'STATESET_KB_API_KEY',
    'STATESET_KB_COLLECTION',
    'ACME_SHOPIFY_ACCESS_TOKEN',
    'ACME_GORGIAS_BASIC_TOKEN',
  ]) {
    delete process.env[key];
  }
}

afterEach(() => {
  resetEnv();
});

describe('workflow-studio secret env', () => {
  it('derives brand-scoped secret env vars from local env and store config', () => {
    const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'stateset-ws-secret-env-'));
    saveIntegrationsStore(cwd, 'local', {
      version: 1,
      integrations: {
        shopify: {
          enabled: true,
          config: {
            shop: 'acme.myshopify.com',
            accessToken: 'shpat_store_token_value',
          },
          updatedAt: new Date().toISOString(),
        },
        gorgias: {
          enabled: true,
          config: {
            domain: 'acme-support',
            email: 'support@acme.test',
            apiKey: 'gorgias-store-key',
          },
          updatedAt: new Date().toISOString(),
        },
      },
    });
    process.env.OPENAI_API_KEY = 'openai-shell-key';

    const plan = buildLocalConnectorSecretEnvPlan('acme', {}, cwd);

    expect(plan.entries).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          name: 'ACME_SHOPIFY_ACCESS_TOKEN',
          available: true,
          source: 'store',
          value: 'shpat_store_token_value',
        }),
        expect.objectContaining({
          name: 'ACME_GORGIAS_BASIC_TOKEN',
          available: true,
          source: 'store',
          value: Buffer.from('support@acme.test:gorgias-store-key', 'utf-8').toString('base64'),
        }),
        expect.objectContaining({
          name: 'OPENAI_API_KEY',
          available: true,
          source: 'shell',
          value: 'openai-shell-key',
        }),
      ]),
    );
  });

  it('renders dotenv output for the local worker environment', () => {
    process.env.SHOPIFY_SHOP_DOMAIN = 'acme.myshopify.com';
    process.env.SHOPIFY_ACCESS_TOKEN = 'shpat_env_token';

    const plan = buildLocalConnectorSecretEnvPlan('acme');
    const dotenv = renderLocalConnectorSecretEnvPlan(plan, 'dotenv');

    expect(dotenv).toContain('# Generated by response CLI for brand acme');
    expect(dotenv).toContain('ACME_SHOPIFY_ACCESS_TOKEN=shpat_env_token');
  });
});
